[project]
name = "jappa-bedrock"
version = "1.0"
packs-dir = "packs"
src-dir = "src"

[[project.authors]]
name = "SegaBASS (segabass65)"
email = "segabass65@proton.me"

[project.urls]
Author = "https://github.com/segabass65"
Repository = "https://github.com/segabass65/jappa-bedrock"
Modrinth = "https://modrinth.com/resourcepack/jappa-bedrock"

[[tool.mc-pack-env.authors]]
name = "SegaBASS (segabass65)"
email = "segabass65@proton.me"

[tool.mc-pack-env.urls]
Author = "https://github.com/segabass65"
Repository = "https://github.com/segabass65/mc-pack-env"
