[project]
name = "jappa-bedrock"
version = "1.0"
license-files = ["LICENSE"]
packages-dir = "packages"
src-dir = "src"

[[project.authors]]
name = "SegaBASS (segabass65)"
email = "segabass65@proton.me"

[project.urls]
Author = "https://github.com/segabass65"
RepositoryMcPackEnv = "https://github.com/segabass65/mc-pack-env"
PackRepository = "https://github.com/segabass65/jappa-bedrock"
